#© 2023 Miguel López

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-miguel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-miguel
  template:
    metadata:
      labels:
        app: prod-stedi-miguel
    spec:
      containers:
        - name: prod-stedi-miguel
          image: gcr.io/cubs-consulting/stedi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-miguel
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-miguel"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: miguel-twilio-dev
                  key: twilio_token
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-miguel-nodeport
spec:
  selector:
    app: prod-stedi-miguel
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-miguel-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-miguel-public
    networking.gke.io/managed-certificates: prod-stedi-miguel-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-miguel-nodeport
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-miguel-certificate
spec:
  domains:
    - miguel.cit262.com
    
